# Generated by Django 4.2 on 2023-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
