# Generated by Django 4.2 on 2023-04-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_fcmtoken_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-created_at']},
        ),
    ]
