# Generated by Django 4.2 on 2023-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_fcmtoken_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
