# Generated by Django 4.2 on 2023-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_fcmtoken_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={},
        ),
    ]
